FROM python:3.8

WORKDIR /app

RUN apt update && apt upgrade -y
RUN pip install -U pip

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT [ "python3", "main.py" ]